"""empty message

Revision ID: 131dd51172a8
Revises: 
Create Date: 2022-03-17 09:19:10.284823

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '131dd51172a8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('locations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('latitude', sa.String(length=100), nullable=False),
    sa.Column('longitude', sa.String(length=100), nullable=True),
    sa.Column('user_id', sa.BIGINT(), nullable=False),
    sa.Column('accuracy', sa.String(), nullable=False),
    sa.Column('status', sa.String(length=100), nullable=True),
    sa.Column('deleted_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('message', sa.String(length=100), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('user_from_id', sa.BIGINT(), nullable=False),
    sa.Column('user_to_id', sa.BIGINT(), nullable=False),
    sa.Column('status', sa.String(length=100), nullable=True),
    sa.Column('deleted_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('is_admin', sa.Integer(), nullable=True),
    sa.Column('is_dev', sa.Integer(), nullable=True),
    sa.Column('is_student', sa.Integer(), nullable=True),
    sa.Column('public_id', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=100), nullable=True),
    sa.Column('deleted_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('public_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_table('messages')
    op.drop_table('locations')
    # ### end Alembic commands ###
